/**
 * Sending DNS records (ST-03) — generated for the domain and the provider actually
 * configured, and not displayed as hardcoded values.
 *
 * The exact DKIM values are specific to each provider account: we give the record
 * when it is deterministic, and the precise instruction when the value has to be
 * fetched from the provider's dashboard.
 *
 * The labels and hints are displayed in the ST-03 DNS table and stay in English:
 * a package has no access to the i18n dictionaries (apps/web/src/i18n), so this
 * text is not localizable today.
 */
import type { MailProvider } from "./providers";

export type DnsRecord = {
  label: string;
  type: "TXT" | "CNAME" | "MX";
  host: string;
  value: string;
  /** true when the value has to be fetched from the provider. */
  fromProvider?: boolean;
  hint?: string;
};

const SPF_INCLUDE: Partial<Record<MailProvider, string>> = {
  resend: "include:amazonses.com",
  brevo: "include:spf.brevo.com",
  mailjet: "include:spf.mailjet.com",
};

export function dnsRecordsFor(params: {
  provider: MailProvider;
  /** Domain of the sending address (the part after @). */
  domain: string;
  smtpHost?: string | null;
}): DnsRecord[] {
  const { provider, domain } = params;
  if (!domain) return [];

  const include =
    SPF_INCLUDE[provider] ??
    (provider === "smtp" && params.smtpHost ? `a:${params.smtpHost}` : "");

  const records: DnsRecord[] = [
    {
      label: "SPF",
      type: "TXT",
      host: "@",
      value: `v=spf1 ${include || "include:your-provider"} ~all`,
      hint: include
        ? "Merge this value into your existing SPF record if you have one — a single SPF per domain."
        : "Replace the include: part with the one your provider gives you.",
      fromProvider: !include,
    },
    {
      label: "DKIM",
      type: provider === "brevo" ? "TXT" : "CNAME",
      host: provider === "brevo" ? `mail._domainkey.${domain}` : `ohd._domainkey.${domain}`,
      value: "",
      fromProvider: true,
      hint:
        provider === "smtp"
          ? "Generated by your mail server (OpenDKIM or equivalent)."
          : "Value supplied by your account — Sending domains section.",
    },
    {
      label: "DMARC",
      type: "TXT",
      host: `_dmarc.${domain}`,
      value: `v=DMARC1; p=none; rua=mailto:dmarc@${domain}`,
      hint: "Start at p=none to observe, then move to quarantine once SPF and DKIM are aligned.",
    },
  ];

  return records;
}

/** Domain of an email address ("Support <a@b.fr>" → "b.fr"). */
export function domainOf(address: string | null | undefined): string {
  if (!address) return "";
  const match = address.match(/<([^>]+)>/);
  const email = (match?.[1] ?? address).trim();
  return email.split("@")[1]?.toLowerCase() ?? "";
}
